fixtures:
  repositories:
    archive:
      repo: "https://github.com/Adaptavist/puppet-archive"
    java:
      repo: "https://github.com/Adaptavist/puppet-java"
      ref: '1.6.0'
    oracle_java:
      repo: 'https://github.com/Adaptavist/puppet-oracle_java.git'
      ref: '1.0.0'
    limits:
      repo: 'https://github.com/Adaptavist/puppet-limits'
    stdlib:
      repo: 'https://github.com/Adaptavist/puppet-stdlib'
    packages_repos:
      repo: 'https://github.com/Adaptavist/puppet-packages_repos.git'
    apt:
      repo: 'https://github.com/Adaptavist/puppet-apt'
    yum:
      repo: 'https://github.com/Adaptavist/puppet-yum'
    puppi:
      repo: 'https://github.com/Adaptavist/puppet-puppi'
    augeas_core:
        repo: "https://github.com/puppetlabs/puppetlabs-augeas_core"
    yumrepo_core:
      repo: "https://github.com/Adaptavist/puppetlabs-yumrepo_core"
  symlinks:
    avstapp: "#{source_dir}"
