fixtures:
  repositories:
    oracle_java:
      repo: 'https://github.com/Adaptavist/puppet-oracle_java.git'
    java:
      repo: 'https://github.com/Adaptavist/puppet-java.git'
    limits:
      repo: 'https://github.com/Adaptavist/puppet-limits'
    stdlib:
      repo: 'https://github.com/Adaptavist/puppet-stdlib'
    packages_repos:
      repo: 'https://github.com/Adaptavist/puppet-packages_repos.git'
    apt:
      repo: 'https://github.com/Adaptavist/puppet-apt'
      ref: '1.8.0'
    yum:
      repo: 'https://github.com/Adaptavist/puppet-yum'
    puppi:
      repo: 'https://github.com/Adaptavist/puppet-puppi'
    archive:
      repo: 'https://github.com/Adaptavist/puppet-archive.git'
  symlinks:
    avstapp: "#{source_dir}"
